/** English profanity roots for workplace team chat moderation. */
export const TEAM_CHAT_ENGLISH_PROFANITY = [
  "asshole",
  "bastard",
  "bitch",
  "bullshit",
  "cock",
  "crap",
  "cunt",
  "damn",
  "dick",
  "fuck",
  "fucking",
  "motherfucker",
  "nigger",
  "piss",
  "pussy",
  "shit",
  "slut",
  "whore",
] as const;

/** Filipino / Tagalog profanity and strong insults common in PH workplaces. */
export const TEAM_CHAT_TAGALOG_PROFANITY = [
  "amputa",
  "animal",
  "bobo",
  "bwisit",
  "engot",
  "gago",
  "hayop",
  "kantot",
  "leche",
  "lintik",
  "peste",
  "pokpok",
  "puta",
  "putang",
  "putangina",
  "putaang",
  "tarantado",
  "tangina",
  "tangina mo",
  "tite",
  "ulol",
  "yawa",
] as const;
